### ISSUE TITLE
Missing function ?

### ISSUE THREAD

**Issue by Gianluke03** [Lysagxra/AnimeUnityDownloader#2]
Most likely i was wrong but i tried to download an anime with a title that contained special characters and when it created the folder with the anime's name within the downloads it didn't skip the special characters but gave an error.
I solved it by modifying the python "general_utils" file by adding a function that ignores special ("most common") characters that cannot be entered to create a folder name and writes an underscore character in their place ("_").

anyway, great program
it saved me a lot of time !😆

[test.txt](https://github.com/user-attachments/files/18110963/test.txt)

**Comment by Lysagxra** [comment]
Can you provide me with the anime you tried to download?
I'd like to replicate the error you encountered.

**Comment by Gianluke03** [comment]
> Puoi fornirmi l'anime che hai provato a scaricare? Vorrei replicare l'errore che hai riscontrato.

All those anime titles that contain special characters that rightly the folders cannot be registered with that name like I tried to download this movie  "https://www.animeunity.to/anime/5779-overlord-the-sacred-kingdom"

and it doesn't work, but updating the file I mentioned before of which I provided a .txt file now no longer gives that type of problem.

Try it yourself by inserting this link as an example

However, I can say that this downloader is really very fast and efficient and I was sorry that it didn't work for this reason

**Comment by Gianluke03** [comment]
If it were possible it would also be nice to see a stopwatch that marks the time when the program starts and when it ends

**Comment by Lysagxra** [comment]
I've updated the `general_utils.py` with the following function:

```python
def sanitize_filename(filename):
    """
    Sanitize a given filename by replacing invalid characters with underscores.
    Handles the invalid characters specific to Windows, macOS, and Linux.

    Args:
        filename (str): The original filename to sanitize.

    Returns:
        str: The sanitized filename with invalid characters replaced by
             underscores.
    """
    invalid_chars_dict = {
        'nt': r'[\\/:*?"<>|]',  # Windows
        'posix': r'[/:]'        # macOS and Linux
    }
    invalid_chars = invalid_chars_dict.get(os.name)
    return re.sub(invalid_chars, '_', filename)
```

This should correctly handle illegal characters for Windows, macOS, and Linux.
Could you double-check if this works for you?

By the way, thanks for opening the issue and reporting this minor bug.

**Comment by Gianluke03** [comment]
> I've updated the `general_utils.py` with the following function:
> 
> ```python
> def sanitize_filename(filename):
>     """
>     Sanitize a given filename by replacing invalid characters with underscores.
>     Handles the invalid characters specific to Windows, macOS, and Linux.
> 
>     Args:
>         filename (str): The original filename to sanitize.
> 
>     Returns:
>         str: The sanitized filename with invalid characters replaced by
>              underscores.
>     """
>     invalid_chars_dict = {
>         'nt': r'[\\/:*?"<>|]',  # Windows
>         'posix': r'[/:]'        # macOS and Linux
>     }
>     invalid_chars = invalid_chars_dict.get(os.name)
>     return re.sub(invalid_chars, '_', filename)
> ```
> 
> This should correctly handle illegal characters for Windows, macOS, and Linux. Could you double-check if this works for you?
> 
> By the way, thanks for opening the issue and reporting this minor bug.



Yes, everything is going as it should now, thank you very much

if possible plss consider adding a stopwatch that keeps the total time of the whole thing. 👌😄

> Se fosse possibile sarebbe anche bello vedere un cronometro che segna l'ora in cui inizia e quando finisce il programma

**Comment by Lysagxra** [comment]
If you want to display the start time and end time, you can encapsulate the main function in  `main.py`, like this:

```python
import time

start = time.time()
time.sleep(2)
end = time.time()
elapsed_time = end - start

print(f"Elapsed time: {elapsed_time:.2f} sec")
```

Just substitute the sleep time with the actual code from the main function.

**Comment by Lysagxra** [comment]
If you want to display the start time and end time, you can encapsulate the main function in  `main.py`, like this:

```python
import time

start = time.time()
time.sleep(2)
end = time.time()
elapsed_time = end - start

print(f"Elapsed time: {elapsed_time:.2f} sec")
```

Just substitute the sleep time with the actual code from the main function.
